apiVersion: v1
kind: Service
metadata:
  name: crystal
spec:
  selector:
    app: crystal
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crystal
  labels:
    app: crystal
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crystal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crystal
    spec:
      containers:
      - image: CONTAINER_IMAGE
        imagePullPolicy: Always
        name: crystal
        ports:
        - containerPort: 3000
          protocol: TCP
